sudo: required
services:
  - docker

language: go

go:
- "1.10"

install:
- go get -t github.com/yinqiwen/test_ci
- go get golang.org/x/mobile/cmd/gomobile
- gomobile init
script:
- export CGO_ENABLED=0
- GOOS=linux GOARCH=amd64 go build github.com/yinqiwen/test_ci
- tar cjf test_ci-${TRAVIS_TAG}.tar.bz2 test_ci

deploy:
  - provider: releases
    api_key:
      secure: XrroDaqNpEyc0gijt2v4NsCxMSobIlwGPMFqIMgWxfvfQk/ycwvyqs2aGxQDwTIY6J9RmpNYWg5xWl3tCwCxdgnwRJqAHrhD//pfjLFU70jjnjlOXfs2W1LAzltMnC4Ll4pnXJAcAYuPtLZ72Q4IbLBGPLnicZQrL3b4zer0KytuRjivN0CbZF+1Wti/PazDyK7LUOimQhQWtC8be43rc/0VdLTmeo0aDRTQtDiZZgzcyjXYFoPR35pfghirEb9tMTOlgdb60lr2072sQPFv8dZv3XS+ipGWigo8+UfaP3TgPMLMFJQMbsT6JXPuATwXrMTVJgkvUAsR9wziy7FDr9XH6slI3HOTX+ZzAQ6G3dARF0jjhhVgtqx+ODj7TqGwPp36zyt0qry74mDbs1zFh3qG7SnDobCmINRGrWIP+O24Eojb4IXWetkymEHaw1/zHiS3Pm7SxPpuXuk9WkvNm3Q/F/ncyK1K1VKU/f0/5dLvJpXpDdjthEZL3UvkZKJfpn2+ERdtNsIZCqq60w/AtIcI/93q6vvoWJ4HbLo59JxLC3kA3aiqRP65MZZOzQ6rHeJoGBv6xJaZvLYO7swuU/EFtgH6UDdZrCX/lGvMKglwrY7YLCLYQ/RAlChNU/i1PR5cod983yi4gCckKHe6MxXiYrI8y+epFxUvRgTHYxE=
    file: 
      - "test_ci-${TRAVIS_TAG}.tar.bz2"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # - provider: heroku
  #   api_key:
  #     secure: "LQZx6US2jzCMT3VsZHBKT3w4vq3dA1iJZ0591pYkUtvtChIBWnYe9F7rn4XInkyCSKRLBBEkQvu7A9qED0KOi0DlsmIOUgZ5d+qMicWeU0OvUNeiQEBj2bX8oa5mYRW3hBznpkLCZBwnXJLrv6A6LpNQYQ1ZvR19rtmTmXAku+s="
  #   strategy: git
  #   app: $HEROKU_APP
  #   skip_cleanup: true
  #   on:
  #     tags: true
  #     condition: $TRAVIS_TAG = 'latest' 

