sudo: required
services:
  - docker

language: go

go:
- "1.10"

env:
  global:
    - secure: "e7IjyptwfaNmHUYAwTZbLjup0FVD6wVOQIggLSOcqYyrbSYKepVJdbvOUfWqdZ3tUWtpHb5H/2a8RkizXHH3mBi4K5/9wlByTGmiKKA05dYbDod3KpiLbPnHK9UjRQydD6wpYJcK0/yguXmFDqYoRIFwmxeqNJ78OydIo7BOxGY=" 
    - secure: "LEmUhd0lO5BPox3+IdBw/u45Z3TtY0arkef6v7q27qcEs3a2p+SuVVElHx4UcU8/AhN3D9jlskB0UZIgZRMfB3xaPCBVvjHh8UwQ13WqrR7524HuU8kin/4vLDdoIEvs2hQaj58slzmdyddKG2dkgCwkpK/J1DBfKHttbYE+ias=" 
    - secure: "MO3eA15Jp2CkN0SiSI5Oo32wioCcVbaWwpxBCgQrkIyV85yakPzhoWlQWvh90QXEU9bBDKlQiTOXfo11G0as7byU8typa5UI7uLG1sGD9l2bBZbFuqorMrvHl5PeOzfjAQuUnn2KNP5RccuaCn+n65ZImhj8oTFrYGmb1VTdgg0=" 
    - secure: "J+GWt852LoGcez5tyuKSZF85IjoV4T/sIXn+0TuVznh8VHhIpjw4wqBDBbvyjeNgree8QYtJ6CR4aVh6T2JnCw6rsFyMoHEjBaRriIYzPBHtKQhvVyceFFsE6Sgn08ldH/x0T4V53TEo+1fG/wTM32OqTCZwnWND1ZvjHFxWxvw="

install:
- go get -t github.com/yinqiwen/test_ci
script:
- export CGO_ENABLED=0
- GOOS=linux GOARCH=amd64 go build github.com/yinqiwen/test_ci
- tar cjf test_ci-${TRAVIS_TAG}.tar.bz2 test_ci

deploy:
  - provider: releases
    api_key:
      secure: YngDT2JlydCG+qb8Ww9wBFyWiLRQJczybNLeoFKluBXKoh1Vu+TZeReMK+rRUjOqOmYV8sNtOnEVSg4+ICeYDNp9fRRwcNKTkp0H+8pH0OynxdH2faCjx1H5U0WQuWqMLQoMSHZ90I0tL40kEJOChLY6WGvwY47YBqi/dsvmTfg=
    file: 
      - "test_ci-${TRAVIS_TAG}.tar.bz2"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      repo: yinqiwen/gsnova
  # - provider: heroku
  #   api_key:
  #     secure: "LQZx6US2jzCMT3VsZHBKT3w4vq3dA1iJZ0591pYkUtvtChIBWnYe9F7rn4XInkyCSKRLBBEkQvu7A9qED0KOi0DlsmIOUgZ5d+qMicWeU0OvUNeiQEBj2bX8oa5mYRW3hBznpkLCZBwnXJLrv6A6LpNQYQ1ZvR19rtmTmXAku+s="
  #   strategy: git
  #   app: $HEROKU_APP
  #   skip_cleanup: true
  #   on:
  #     tags: true
  #     condition: $TRAVIS_TAG = 'latest' 

